SELECT f.FLAVOR 
FROM FIRST_HALF as f,
(SELECT FLAVOR, sum(TOTAL_ORDER) as TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) as j
WHERE f.FLAVOR = j.FLAVOR
ORDER BY f.TOTAL_ORDER + j.TOTAL_ORDER DESC
LIMIT 3;